# Generated by Django 5.1.1 on 2024-09-15 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libraryMS', '0003_alter_review_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_type', models.CharField(choices=[('most_borrowed_books', 'Most Borrowed Books'), ('borrowers_with_overdue_books', 'Borrowers with Overdue Books'), ('books_currently_checked_out', 'Books Currently Checked Out'), ('books_in_high_demand', 'Books in High Demand'), ('borrowing_trends', 'Borrowing Trends')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='reports/')),
                ('generated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
